#!/bin/sh

# Reposition screens
xrandr --output DisplayPort-0 --primary --mode 2560x1440 --pos 2560x0 --rotate normal --output DVI-1 --off --output DVI-0 --mode 2560x1440 --pos 0x0 --rotate normal --output HDMI-0 --off

# Remap caps to escape
setxkbmap -option caps:escape

# Increase key repeat rate
xset r rate 250 50
